Repository GSG-G13/memes-generator, pull requests merged in 2023-03, with the labels that each got.

#5 create readme file
  README.md
Labels: waiting review

#9 1 create files structure
  css/style.css
  html/index.html
  html/meme.html
  js/dom.js
  js/logic.js
Labels: done, reviewed

#10 create main page html and css
  css/style.css
  html/index.html
  wxica.jpg
Labels: request change

#12 show to joke every time you reload
  html/index.html
  js/dom.js
  js/logic.js
Labels: waiting review

#13 create meme page
  css/style.css
  html/meme.html
  js/dom.js
Labels: waiting review

#15 fetch api
  js/logic.js
Labels: waiting review

#31 Make text editable
  css/style.css
  js/dom.js
  js/logic.js
  meme.html
Labels: waiting review
